#!/bin/bash

DOTFILES="$HOME/.dotfiles"

hash git 2>&- || { echo >&2 "Git is required but missing."; exit 1; }

if [[ ! -d $DOTFILES ]]; then
	git clone -q git://github.com/davgothic/dotfiles.git $DOTFILES
	[[ ! -d $DOTFILES ]] && { echo >&2 "Could not clone the dotfiles repository."; exit 1; }
fi

cd $DOTFILES && git pull -q && git submodule update -q --init --recursive

FILES=$(find $DOTFILES -mindepth 1 -maxdepth 1 | grep -Ev '(\.git|install|README)')
for FILE in $FILES; do
	FILENAME=".$(basename $FILE)"

	if [[ -f "$HOME/$FILENAME" && ! -f "$HOME/$FILENAME.bak" ]]; then
		mv "$HOME/$FILENAME" "$HOME/$FILENAME.bak"
	fi

	if [[ -f "$HOME/$FILENAME" || -d "$HOME/$FILENAME" ]]; then
		rm -r "$HOME/$FILENAME"
	fi

	ln -s $FILE "$HOME/$FILENAME"
done
unset DOTFILES
unset FILES

. "$HOME/.bashrc"
